@startuml
actor Alice as A
entity "Wallet Alice" as WA
entity "Channel Service Alice" as CSA
entity "Payment Channel" as PC
entity "Channel Service Bob" as CSB
entity "Wallet Bob" as WB
actor Bob as B

skinparam sequenceReferenceBackgroundColor wheat

title Close Channel

note across: We assume the happy case where both parties always accept signature requests.

[-\\ "alive signal"
activate PC #yellow
A -> WA : Request channel close
activate WA #pink
WA -> CSA : rpc call CloseChannel()
activate CSA #lightgreen
CSA -> WA : rpc call SignMessage() w/ ChannelClose
activate WA #mediumorchid
ref over A, WA, CSA : SignMessage() procedure
WA -> CSA : return signed ChannelClose
deactivate WA
CSA -> CSB : publish channel close request
activate CSB #lightgreen
CSB -> WB : rpc call CloseChannel()
activate WB #pink
activate WB #mediumorchid
WB -> B : request close request acceptance/declination
alt#gold #lightblue on channel close acceptance
  B -> WB : accept channel close
  WB -> CSB : return channel close acceptance
  deactivate WB
  CSB -> WB : rpc call SignMessage() w/ ChannelClose
  activate WB #sandybrown
  ref over B, WB, CSB : SignMessage() procedure
  WB -> CSB : return signed ChannelClose
  deactivate WB
  CSB -> CSA : publish successful channel close
  CSA -> WA : rpc call SignTransaction() w/ ChannelClose TX
  activate WA #mediumorchid
  ref over A, CSA, WA : SignTransaction() procedure
  WA -> CSA : return signed TX
  deactivate WA
  CSA -> PC : publish ChannelClose TX
  PC -> CSA : emit ChannelSettlement event
  PC -> CSB : emit ChannelSettlement event
  note over PC: "Successfully closed channel"
  destroy PC
  CSA -> WA : return successful channel close
  deactivate CSA
  WA -> A : notify successful channel close
  deactivate WA
  CSB -> WB : notify successful channel close
  deactivate CSB
  WB -> B : notify successful channel close
  deactivate WB
else #salmon on channel close declination
  [-\\ "alive signal"
  activate PC #yellow
  activate WB #pink
  activate WB #mediumorchid
  activate CSB #lightgreen
  activate WA #pink
  activate CSA #lightgreen
  WB -> CSB : return close declination
  deactivate WB
  deactivate WB
  CSB -> CSA : publish unsuccessful channel close
  deactivate CSB
  CSA -> WA : return unsuccessful channel close
  deactivate CSA
  WA -> A : notify unsuccessful channel close
  deactivate WA
  note across: "Enter <Channel Force Close> sequence diagram entry"
end
deactivate PC


@enduml
