@startuml
actor Alice as A
entity "Wallet Alice" as WA
entity "Channel Service Alice" as CSA
entity "Payment Channel" as PC
entity "Channel Service Bob" as CSB
entity "Wallet Bob" as WB
actor Bob as B

title Open Channel

A -> WA : request open channel
activate WA #pink
WA -> CSA : rpc call OpenChannel()
activate CSA #lightgreen
CSA -> CSB : publish OpenChannel request
activate CSB #lightgreen
CSB -> WB : rpc call ForwardOpenChannelRequest
activate WB #pink
WB -> B : Request open channel acceptance/declination
alt#gold #lightblue on channel open acceptance
  B -> WB : Accept open channel request
  WB -> CSB : rpc call OpenChannel()
  activate CSB #darkgreen
  CSB -> CSA : publish open channel acceptance
  CSA -> PC : Open Channel
  CSB -> WB : return successful open channel
  deactivate CSB
  deactivate CSB
  WB -> B : notify successful open channel
  deactivate WB
  CSA -> WA : return successful open channel
  deactivate CSA
  WA -> A : notify successful open channel
  deactivate WA
  activate PC #yellow
  note over PC: Channel is established
  PC -> PC : established
  deactivate PC
else #salmon on channel open declination
  [-\\ "alive signal"
  activate CSA #lightgreen
  activate CSB #lightgreen
  activate WB #pink
  activate WA #pink
  B -> WB : Decline open channel request
  WB -> CSB : rpc call OpenChannel() w/ Declination
  activate CSB #darkgreen
  CSB -> CSA : publish OpenChannel declination
  CSB -> WB : return
  deactivate CSB
  deactivate CSB
  deactivate WB
  CSA -> WA : return open channel declination
  deactivate CSA
  WA -> A : notify open channel declination
  deactivate WA
end

@enduml
